import Head from 'next/head';

import { 
    Navbar, 
    NavigationDots, 
    Header, 
    About, 
    Technologies, 
    Projects, 
    Footer 
} from '../components';

import { 
    getProjects, 
    getTechnologies, 
    getAbouts,
    useCurrentSection
} from '../lib';

export default function Home({ projects, technologies, abouts }) {
    const { 
        currentSection,
        aboutRef,
        technologiesRef,
        projectsRef,
        headerRef,
        contactRef,
        onChangeCurrentSection,
    } = useCurrentSection();

    return (
        <>
            <Head>
                <title>Serey Roth&apos; Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='w-screen min-h-screen flex flex-col items-center
            bg-gradient-to-b from-indigo-500/20'>
                <Navbar />

                <div className='fixed top-1/2 right-5 z-[5] -translate-y-1/2'>
                    <NavigationDots
                        currentSectionIndex={currentSection}
                        onClick={onChangeCurrentSection} />
                </div>

                <Header ref={headerRef}/>

                <About 
                    ref={aboutRef} 
                    abouts={abouts} />


                <Projects 
                    ref={projectsRef} 
                    projects={projects} />

                <Technologies 
                    ref={technologiesRef} 
                    technologies={technologies} />

                <Footer ref={contactRef} />
            </main>
        </>
    )
};

export async function getServerSideProps() {
    const projects = await getProjects();
    const technologies = await getTechnologies();
    const abouts = await getAbouts();
    
    return {
        props: {
            projects,
            technologies,
            abouts,
        }
    }
};
