import Head from 'next/head'

import About from '../components/About'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Navbar from '../components/Navbar'
import Projects from '../components/Projects'
import Technologies from '../components/Technologies'

import { client } from '../lib/client'

export default function Home({ projects }) {
    return (
        <>
            <Head>
                <title>Serey Roth&apos; Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='w-screen min-h-screen flex flex-col items-center'>
                <Navbar />
                <Header />
                <Projects projects={projects} />
                <Technologies />
                <Footer />
            </main>
        </>
    )
}

export async function getServerSideProps() {
    const projectQuery = `*[_type == 'project']{ 
        ...,
        "tools":tools[]->{name, icon} 
    }`;
    
    const projects = await client.fetch(projectQuery);

    return {
        props: {
            projects
        }
    }
}
